version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5433:5432'
    expose:
      - '5433'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: labelsync
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
