version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: labelsync
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
volumes:
  postgres:
