export default {
  action: 'labeled',
  issue: {
    id: 586553190,
    node_id: 'MDU6SXNzdWU1ODY1NTMxOTA=',
    number: 1,
    title: 'LabelSync - Invalid configuration',
    user: {
      login: 'labelsync-manager',
      id: 55896118,
      node_id: 'MDM6Qm90NTU4OTYxMTg=',
      avatar_url: 'https://avatars0.githubusercontent.com/in/42297?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/labelsync-manager%5Bbot%5D',
      html_url: 'https://github.com/apps/labelsync-manager',
      received_events_url:
        'https://api.github.com/users/labelsync-manager%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2020-03-23T22:17:15Z',
    updated_at: '2020-03-24T07:24:21Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    body: '',
  },
  label: {
    id: 1929933064,
    node_id: 'MDU6TGFiZWwxOTI5OTMzMDY0',
    url:
      'https://api.github.com/repos/3-SemicolonClub/3-SemicolonClub-labelsync/labels/documentation',
    name: 'label/siblings',
    color: '0075ca',
    default: true,
    description: 'Improvements or additions to documentation',
  },
  repository: {
    id: 249556373,
    node_id: 'MDEwOlJlcG9zaXRvcnkyNDk1NTYzNzM=',
    name: 'changed',
    full_name: 'maticzav/changed',
    private: false,
    owner: {
      login: 'maticzav',
      id: 43337079,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjQzMzM3MDc5',
      avatar_url: 'https://avatars0.githubusercontent.com/u/43337079?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/3-SemicolonClub',
      html_url: 'https://github.com/3-SemicolonClub',
      received_events_url:
        'https://api.github.com/users/3-SemicolonClub/received_events',
      type: 'Organization',
      site_admin: false,
    },
    html_url: 'https://github.com/3-SemicolonClub/3-SemicolonClub-labelsync',
    description: 'LabelSync configuration repository.',
    fork: false,
    deployments_url:
      'https://api.github.com/repos/3-SemicolonClub/3-SemicolonClub-labelsync/deployments',
    created_at: '2020-03-23T22:17:05Z',
    updated_at: '2020-03-23T22:17:15Z',
    pushed_at: '2020-03-23T22:17:13Z',
    git_url: 'git://github.com/3-SemicolonClub/3-SemicolonClub-labelsync.git',
    ssh_url: 'git@github.com:3-SemicolonClub/3-SemicolonClub-labelsync.git',
    clone_url:
      'https://github.com/3-SemicolonClub/3-SemicolonClub-labelsync.git',
    svn_url: 'https://github.com/3-SemicolonClub/3-SemicolonClub-labelsync',
    homepage: null,
    size: 2,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 1,
    license: null,
    forks: 0,
    open_issues: 1,
    watchers: 0,
    default_branch: 'master',
  },
  organization: {
    login: 'maticzav',
    id: 43337079,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjQzMzM3MDc5',
    url: 'https://api.github.com/orgs/3-SemicolonClub',
    public_members_url:
      'https://api.github.com/orgs/3-SemicolonClub/public_members{/member}',
    avatar_url: 'https://avatars0.githubusercontent.com/u/43337079?v=4',
    description: '{ semi: true }',
  },
  sender: {
    login: 'maticzav',
    id: 3924224,
    node_id: 'MDQ6VXNlcjM5MjQyMjQ=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/3924224?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/maticzav',
    html_url: 'https://github.com/maticzav',
    followers_url: 'https://api.github.com/users/maticzav/followers',
    type: 'User',
    site_admin: false,
  },
  installation: {
    id: 7501122,
    node_id: 'asd==',
  },
}
