import chalk from 'chalk'
import ml from 'multilines'
import { GithubLabel, GithubRepository } from '../../github'
import { RepositoryConfig } from '../../types'

import { LabelSyncOptions } from './sync'

export type LabelSyncReport = {
  repository: GithubRepository
  config: RepositoryConfig
  options: LabelSyncOptions
  additions: GithubLabel[]
  updates: GithubLabel[]
  removals: GithubLabel[]
}

/**
 *
 * Creates a human readable terminal report of Label Sync.
 * (Uses chalk to make report more lively.)
 *
 * @param report
 */
export function createTerminalReport(report: LabelSyncReport): string {
  const strictMessage = ml`
    | We haven't removed any label yet.
    | If you want us to remove them, set ${chalk.redBright('strict')} to true.
  `

  /* Shorten the report if no changes have been made. */
  if (
    report.additions.length === 0 &&
    report.updates.length === 0 &&
    report.removals.length === 0
  ) {
    return ml`
    | No changes to labels in the repository.
    `
  }

  return ml`
    | ${chalk.gray('This is an autogenerated report for your project.')}
    | (dry run: "${report.options.dryRun}")
    | 
    | ${chalk.bgMagenta(`New Labels: (${report.additions.length})`)}
    | ${labelsList(report.additions) || 'No new labels.'}
    |
    | ${chalk.bgMagenta(`Updated Labels: (${report.updates.length})`)}
    | ${labelsList(report.updates) || 'No updated labels.'}
    |
    | ${chalk.bgMagenta(`Removed Labels: (${report.removals.length})`)}
    | ${labelsList(report.removals) || 'No removed labels.'}
    |
    | ${!report.config.strict ? strictMessage : ''}
  `

  function labelsList(labels: GithubLabel[]): string {
    return labels
      .map(label => {
        if (label.description === '') {
          return `- ${chalk.hex(label.color)(label.name)}`
        }

        return ml`
        | - ${chalk.hex(label.color)(label.name)}
        |   ${chalk.gray(label.description)}
        `
      })
      .join('\n')
  }
}
