import chalk from 'chalk'
import {
  SyncReport,
  RepositorySyncSuccessReport,
  RepositorySyncErrorReport,
} from './handlers'
import { GithubLabel } from './labels'

/**
 *
 * Generates human readable sync report.
 *
 * @param reports
 */
export function generateSyncReport(report: SyncReport) {
  const message = `
# Github Labels Report

> This is an autogenerated report for your project.

Hey :wave: we ran sync and this came out:

### Problems

${generateRepositorySyncErrorsReport(report.errors)}

### Updates

${generateRepositorySyncSuccessesReport(report.successes)}
      `

  return message

  /**
   * Helper functions
   */
  function generateRepositorySyncSuccessesReport(
    reports: RepositorySyncSuccessReport[],
  ): string {
    if (reports.length === 0) {
      return `No successful sync reports.`
    }

    return `
Successfully synced labels accross ${reports.length} repositories;
${reports.map(generateRepositorySyncSuccessReport).join('\n\n')}
    `
  }

  function generateRepositorySyncErrorsReport(
    reports: RepositorySyncErrorReport[],
  ): string {
    if (reports.length === 0) {
      return `Everything looks fine.`
    }

    return `
There were some issues with ${reports.length} repositories;
${reports.map(generateRepositorySyncErrorReport).join('\n\n')}
    `
  }

  function generateRepositorySyncSuccessReport(
    report: RepositorySyncSuccessReport,
  ): string {
    const message = `
Synced ${report.name}:
  
${generateLabelsSyncReport({ action: 'add', labels: report.additions })}
  
${generateLabelsSyncReport({ action: 'update', labels: report.updates })}
  
${generateLabelsSyncReport({
      action: 'remove',
      labels: report.removals,
      warn: report.config.strict!,
    })}
    `

    return message
  }

  function generateRepositorySyncErrorReport(
    report: RepositorySyncErrorReport,
  ): string {
    const message = `
Couldn't sync ${report.name}:

${report.message}

### Configuration

${codeBlock(JSON.stringify(report.config, null, 2), 'json')}

    `
    return message
  }

  function generateLabelsSyncReport(
    options:
      | { action: 'add'; labels: GithubLabel[] }
      | { action: 'update'; labels: GithubLabel[] }
      | { action: 'remove'; labels: GithubLabel[]; warn: boolean },
  ) {
    switch (options.action) {
      case 'add': {
        if (options.labels.length === 0) {
          return `No new labels.`
        }

        return `
Added ${options.labels.length} labels:
${options.labels.map(generateLabelSyncReport)}
        `
      }

      case 'update': {
        if (options.labels.length === 0) {
          return `No labels updated.`
        }

        return `
Updated ${options.labels.length} labels:
${options.labels.map(generateLabelSyncReport)}
        `
      }

      case 'remove': {
        if (options.labels.length === 0) {
          return `No labels removed.`
        }

        if (options.warn) {
          return `
${options.labels.length} labels should be removed;
${options.labels.map(generateLabelSyncReport)}

To remove them, set "strict" property to true in repository configuration.
    `
        } else {
          return `
Removed ${options.labels.length} labels:
${options.labels.map(generateLabelSyncReport)}
                  `
        }
      }
    }
  }

  function generateLabelSyncReport(label: GithubLabel): string {
    return chalk.hex(label.color)(` - ${label.name}\n`)
  }

  /**
   * Utils
   */
  function codeBlock(code: string, language: string): string {
    return '```' + language + `\n` + code + '```'
  }
}
