# on:
#   push:
#     branches:
#       - master

# name: Release
# jobs:
#   build:
#     name: release
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '13.x'
#       - run: yarn install
#       - run: yarn test
#       - run: npx semantic-release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
